### ISSUE TITLE
application crashes after recording starts

### ISSUE THREAD

**Issue by Wjxfi** [Myzel394/Alibi#1]
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: app.myzel394.alibi, PID: 26266
java.lang.IllegalArgumentException: app.myzel394.alibi: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
	at b3.e.h(SourceFile:229)
	at b3.e.k0(SourceFile:13)
	at kotlinx.coroutines.flow.m.h(Unknown Source:43)
	at kotlinx.coroutines.flow.m.f0(SourceFile:18)
	at d5.j.h(SourceFile:35)
	at d5.j.k0(SourceFile:13)
	at a5.a.e0(SourceFile:28)
	at a5.y.a1(SourceFile:47)
	at a5.y.b1(Unknown Source:11)
	at d5.l.e(Unknown Source:105)
	at d5.u.f0(SourceFile:5)
	at d5.t.j(SourceFile:135)
	at d5.t.e(Unknown Source:0)
	at n2.t.e(SourceFile:177)
	at kotlinx.coroutines.flow.l.e(Unknown Source:125)
	at kotlinx.coroutines.flow.l0.a(SourceFile:172)
	at n2.v.h(SourceFile:81)
	at n2.v.k0(SourceFile:13)
	at kotlinx.coroutines.flow.g.a(SourceFile:91)
	at d5.m.h(Unknown Source:46)
	at d5.m.k0(SourceFile:13)
	at o4.a.g1(SourceFile:5)
	at a5.y.g0(Unknown Source:9)
	at d5.n.g(Unknown Source:6)
	at d5.e.h(SourceFile:45)
	at j4.a.n(Unknown Source:8)
	at a5.e0.run(Unknown Source:104)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: a5.c0: [m1{Cancelling}@6322c45, Dispatchers.IO]

**Comment by Myzel394** [comment]
First user! :partying_face: You are so fast, that I wasn't even able to publish the app to IzzyOnDroid yet! :D But thanks to you I can fix this bug now before a broader audience of people sees it, thanks for opening the issue!

What OS are you running this on (GrapheneOS, LineageOS, Stock Android, etc.)? And what Android version?

**Comment by Retardium** [comment]
Hello, I have a related or maybe the same bug.
The app crash when I press "start recording". 
Permissons are permitted and I use CalyxOS 4.10.0 (Android 13). I've installed your app from Izzys repo. 😊

Crash log:
`java.lang.IllegalArgumentException: app.myzel394.alibi: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
	at b3.e.h(SourceFile:229)
	at b3.e.k0(SourceFile:13)
	at kotlinx.coroutines.flow.m.h(Unknown Source:43)
	at kotlinx.coroutines.flow.m.f0(SourceFile:18)
	at d5.j.h(SourceFile:35)
	at d5.j.k0(SourceFile:13)
	at a5.a.e0(SourceFile:28)
	at a5.y.a1(SourceFile:47)
	at a5.y.b1(Unknown Source:11)
	at d5.l.e(Unknown Source:105)
	at d5.u.f0(SourceFile:5)
	at d5.t.j(SourceFile:135)
	at d5.t.e(Unknown Source:0)
	at n2.t.e(SourceFile:177)
	at kotlinx.coroutines.flow.l.e(Unknown Source:125)
	at kotlinx.coroutines.flow.l0.a(SourceFile:172)
	at n2.v.h(SourceFile:81)
	at n2.v.k0(SourceFile:13)
	at kotlinx.coroutines.flow.g.a(SourceFile:91)
	at d5.m.h(Unknown Source:46)
	at d5.m.k0(SourceFile:13)
	at o4.a.g1(SourceFile:5)
	at a5.y.g0(Unknown Source:9)
	at d5.n.g(Unknown Source:6)
	at d5.e.h(SourceFile:45)
	at j4.a.n(Unknown Source:8)
	at a5.e0.run(Unknown Source:104)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: a5.c0: [m1{Cancelling}@4ce986f, Dispatchers.IO]
`

**Comment by fexx1** [comment]
Hey man, same stuff here from Izzy AND GitHub!

API Level 33

**Comment by Myzel394** [comment]
Sorry to hear that, I have released a new update which should fix this issue. Available on GitHub in about 10 minutes, will by synced by IzzyOnDroid in about ~11 hours

**Comment by fexx1** [comment]
Thank You!

Working now v0.1.1

A13

**Comment by Myzel394** [comment]
@serrq are you using the latest update from GitHub?

**Comment by Retardium** [comment]
Yep, it's working now. Thanks for the fast fix!
