### ISSUE TITLE
Crash when Alibi starts a new Batch

### ISSUE THREAD

**Issue by materialred** [Myzel394/Alibi#14]
Alibi crashes after the Batch duration has expired.

```
--------- beginning of main
[ 08-16 16:18:15.329  6306: 6306 E/.myzel394.alibi ]
Not starting debugger since process cannot load the jdwp agent.

--------- beginning of crash
[ 08-16 16:19:18.999  6306: 6306 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: app.myzel394.alibi, PID: 6306
java.lang.IllegalStateException
	at android.media.MediaRecorder.getMaxAmplitude(Native Method)
	at d3.b.c(SourceFile:19)
	at d3.a.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

Samsung Galaxy a20e

LineageOS 20 (Android 13)

**Comment by Myzel394** [comment]
Should be fixes in version `0.2.1`
