### ISSUE TITLE
Crash when changing Sampling rate

### ISSUE THREAD

**Issue by materialred** [Myzel394/Alibi#48]
Alibi crashes when i try to set the sampling rate above 9999999999 insted of showing that the number is to big. If i try to empty the input field completly, Alibi also crashes.

`FATAL EXCEPTION: main
Process: app.myzel394.alibi, PID: 6324
java.lang.NullPointerException
	at e4.b.a(SourceFile:66)
	at e4.b.t0(SourceFile:16)
	at a5.e.a(SourceFile:8)
	at b5.c.h(SourceFile:36)
	at l5.a.m(SourceFile:1)
	at c6.e0.run(SourceFile:1)
	at androidx.compose.ui.platform.s0.f(SourceFile:23)
	at androidx.compose.ui.platform.r0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7929)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
	Suppressed: c6.c0: [androidx.compose.ui.platform.r1@81560cd, h0.e@26dd82, m1{Cancelling}@c961c93, s0@55124d0]`

**Comment by Myzel394** [comment]
Well, that number is indeed too big, I'm not sure if even a highly specialized microphone would be able to do that, let alone a phone :O

You're right it shouldn't crash, I'll take a look at it.
